name: urwid-assets
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.11,<4.0
  - urwid
  - injector
  - cryptography
  - aiohttp
  # The following are not really dependencies but are used in testing, etc
  - requests
  - python-dateutil
